import Link from "next/link";
import {
  AlertTriangle,
  ArrowLeft,
  CheckCircle2,
  Coins,
  FileText,
  Scale,
  ShieldCheck,
} from "lucide-react";

import PageContainer from "@/components/layout/PageContainer";

const sections = [
  {
    title: "1. INTRODUCTION",
    body: [
      "The Richlance Revenue Share Token (RST) is a digital revenue-share asset developed by Richlance International Limited.",
      "RST enables eligible participants to share in the growth and revenue generated by the Richlance ecosystem in accordance with these Terms.",
      "RST does not represent ownership or equity in Richlance International Limited.",
    ],
  },
  {
    title: "2. ELIGIBILITY",
    bullets: [
      "Be at least 18 years old.",
      "Have legal capacity to contract.",
      "Comply with applicable laws.",
      "Complete KYC where required.",
    ],
  },
  {
    title: "3. RST SUBSCRIPTION",
    bullets: [
      "Subscription Currency: USDT",
      "Initial Price: US$1 per RST",
      "Minimum Subscription: US$10",
      "Maximum Supply: 10,000,000 RST",
      "No Minting.",
    ],
    subTitle: "Subscription Allocation:",
    subBullets: [
      "30% Redemption Pool",
      "30% Richlance Ecosystem",
      "10% Richcoin Buyback & Burn",
      "10% Richcoin Referral Pool",
      "10% Richcoin Staking Pool",
      "10% Richlance Supplement Products",
    ],
  },
  {
    title: "4. MONTHLY PROFIT ALLOCATION",
    body: ["20% of Eligible Net Platform Profit is allocated as follows:"],
    bullets: [
      "50% Redemption Pool",
      "25% Richcoin Buyback & Burn",
      "12.5% Richcoin Referral Pool",
      "12.5% Richcoin Staking Pool",
    ],
  },
  {
    title: "5. OPV",
    body: [
      "Official Programme Value (OPV) is determined by Redemption Pool growth and programme metrics.",
      "Illustrations are examples only and are not guarantees.",
    ],
  },
  {
    title: "6. 90-DAY GROWTH PERIOD",
    body: [
      "No profit claims or redemptions are available during the first 90 days.",
      "After 90 days, 10% of the holder's portfolio becomes available in the Claim Wallet as RST.",
      "When claimed, the system purchases the equivalent value in Richcoin (RIC) and credits the holder's Richcoin Wallet.",
    ],
  },
  {
    title: "7. PROFIT PAYMENTS",
    body: [
      "All profit distributions and redemption payments are made exclusively in Richcoin (RIC).",
    ],
  },
  {
    title: "8. HEALTH REWARD",
    body: [
      "5% of every profit claim is automatically credited to the user's Health Reward Wallet and can only be used to redeem eligible Richlance products.",
    ],
  },
  {
    title: "9. MAXIMUM RETURN POLICY",
    body: [
      "Each subscription ends automatically once total withdrawn profits reach ten (10) times the initial subscription amount.",
      "New subscriptions may be created at any time.",
    ],
  },
  {
    title: "10. VOLUNTARY TERMINATION",
    body: [
      "Upon voluntary termination, future revenue-share rights are permanently forfeited.",
      "The original subscription amount is refunded over twelve (12) equal monthly instalments.",
    ],
  },
  {
    title: "11. MULTIPLE SUBSCRIPTIONS",
    body: [
      "Users may maintain multiple subscriptions, each operating independently.",
    ],
  },
  {
    title: "12. SHAREHOLDER DASHBOARD",
    body: [
      "The Shareholder Dashboard displays Portfolio Value, OPV, Redemption Pool Growth, Profit History, Ecosystem Performance and Claim History.",
    ],
  },
  {
    title: "13. FEES",
    bullets: ["Buy Fee: 2.5%", "Profit Claim Fee: 2.5%"],
  },
  {
    title: "14. RISKS",
    body: [
      "Participation involves risk.",
      "Richlance does not guarantee profits, appreciation or preservation of capital.",
    ],
  },
  {
    title: "15. COMPLIANCE",
    body: [
      "Illegal activities, fraud, money laundering and sanctions violations are prohibited.",
    ],
  },
  {
    title: "16. AMENDMENTS",
    body: ["Richlance may amend these Terms from time to time."],
  },
  {
    title: "17. LIMITATION OF LIABILITY",
    body: [
      "Richlance shall not be liable for blockchain failures, third-party service interruptions, cyber incidents beyond reasonable control, force majeure or market conditions.",
    ],
  },
  {
    title: "18. INTELLECTUAL PROPERTY",
    body: [
      "All Richlance branding, software and content remain the property of Richlance International Limited.",
    ],
  },
  {
    title: "19. GOVERNING LAW",
    body: [
      "These Terms are governed by the applicable laws governing Richlance International Limited.",
    ],
  },
  {
    title: "20. DISCLAIMER",
    body: [
      "RST is a digital revenue-share asset and is not a traditional company share, equity, bank deposit or guaranteed investment.",
      "Illustrations are examples only and do not guarantee future performance.",
    ],
  },
  {
    title: "21. ACCEPTANCE",
    body: [
      'By selecting "I Agree", you confirm that you have read, understood and accepted these Terms & Conditions.',
    ],
  },
];

function SummaryCard({
  icon: Icon,
  title,
  text,
}: {
  icon: typeof FileText;
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
      <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#1250FF]/15 text-[#4EA1FF]">
        <Icon size={20} />
      </div>
      <h3 className="mt-4 text-sm font-black text-white">{title}</h3>
      <p className="mt-2 text-sm leading-6 text-[#A4AAB7]">{text}</p>
    </div>
  );
}

function TermsSection({
  title,
  body,
  bullets,
  subTitle,
  subBullets,
}: {
  title: string;
  body?: string[];
  bullets?: string[];
  subTitle?: string;
  subBullets?: string[];
}) {
  return (
    <section className="rounded-2xl border border-white/10 bg-[#10131A] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
      <h2 className="text-base font-black tracking-wide text-white">{title}</h2>

      {body?.map((item) => (
        <p key={item} className="mt-3 text-sm leading-7 text-[#C8CDD8]">
          {item}
        </p>
      ))}

      {bullets ? (
        <ul className="mt-4 space-y-2">
          {bullets.map((item) => (
            <li key={item} className="flex gap-3 text-sm leading-6 text-[#C8CDD8]">
              <CheckCircle2
                size={16}
                className="mt-1 shrink-0 text-[#19C46B]"
              />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      ) : null}

      {subTitle ? (
        <p className="mt-5 text-sm font-black text-white">{subTitle}</p>
      ) : null}

      {subBullets ? (
        <div className="mt-3 grid gap-2 sm:grid-cols-2">
          {subBullets.map((item) => (
            <div
              key={item}
              className="rounded-xl border border-white/10 bg-[#070B12] px-4 py-3 text-sm font-semibold text-[#D4D8E2]"
            >
              {item}
            </div>
          ))}
        </div>
      ) : null}
    </section>
  );
}

export default function RstTermsPage() {
  return (
    <PageContainer>
      <main className="-mx-2 space-y-5 pb-8 sm:mx-0">
        <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#070B12] p-5 sm:p-7">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(18,80,255,0.28),transparent_35%),radial-gradient(circle_at_10%_10%,rgba(25,196,107,0.12),transparent_28%)]" />

          <div className="relative z-10">
            <Link
              href="/rst"
              className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-4 py-2 text-sm font-black text-white transition hover:bg-white/[0.06]"
            >
              <ArrowLeft size={16} />
              Back to RST
            </Link>

            <div className="mt-7 max-w-3xl">
              <div className="inline-flex items-center gap-2 rounded-full border border-[#1250FF]/25 bg-[#1250FF]/10 px-4 py-2 text-xs font-black uppercase tracking-[0.2em] text-[#4EA1FF]">
                <FileText size={15} />
                Terms & Conditions
              </div>

              <h1 className="mt-5 text-3xl font-black leading-tight text-white sm:text-5xl">
                Richlance Revenue Share Token{" "}
                <span className="text-[#4EA1FF]">(RST)</span>
              </h1>

              <p className="mt-5 max-w-2xl text-sm leading-7 text-[#C8CDD8] sm:text-base">
                By subscribing to the Richlance Revenue Share Token (RST), you
                acknowledge that you have read, understood, and agreed to these
                Terms & Conditions.
              </p>
            </div>
          </div>
        </section>

        <section className="grid gap-3 md:grid-cols-3">
          <SummaryCard
            icon={Coins}
            title="Digital Revenue-Share Asset"
            text="RST enables eligible participants to share in Richlance ecosystem revenue, subject to these Terms."
          />
          <SummaryCard
            icon={ShieldCheck}
            title="RIC-Based Payments"
            text="Profit distributions and redemption payments are made exclusively in Richcoin (RIC)."
          />
          <SummaryCard
            icon={Scale}
            title="Risk Acknowledgement"
            text="RST is not equity, a bank deposit, or a guaranteed investment. Participation involves risk."
          />
        </section>

        <section className="rounded-2xl border border-[#F6B73C]/20 bg-[#F6B73C]/10 p-5">
          <div className="flex gap-3">
            <AlertTriangle className="mt-0.5 shrink-0 text-[#F6B73C]" size={22} />
            <div>
              <h2 className="text-base font-black text-white">
                Important Disclaimer
              </h2>
              <p className="mt-2 text-sm leading-7 text-[#F4D79D]">
                RST does not represent ownership or equity in Richlance
                International Limited. Illustrations are examples only and do not
                guarantee future performance.
              </p>
            </div>
          </div>
        </section>

        <div className="grid gap-4">
          {sections.map((section) => (
            <TermsSection key={section.title} {...section} />
          ))}
        </div>

        <section className="rounded-3xl border border-[#1250FF]/20 bg-[linear-gradient(135deg,rgba(18,80,255,0.2),rgba(6,10,18,0.96))] p-6 text-center">
          <h2 className="text-xl font-black text-white">Acceptance</h2>
          <p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-[#C8CDD8]">
            By selecting "I Agree", you confirm that you have read, understood
            and accepted these Terms & Conditions.
          </p>

          <Link
            href="/rst"
            className="mt-6 inline-flex h-12 items-center justify-center rounded-xl bg-[#1250FF] px-8 text-sm font-black text-white shadow-[0_14px_30px_rgba(18,80,255,0.28)] transition hover:bg-[#0F46DD]"
          >
            Return to RST Subscription
          </Link>
        </section>
      </main>
    </PageContainer>
  );
}
